# Generated by Django 4.0.5 on 2022-06-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='word',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
