# Generated by Django 4.0.5 on 2022-06-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0002_profile_full_name_profile_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('chat_id', 'word')},
        ),
    ]
